spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5433/accounts
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

topic:
  accounts: new_accounts_topic
  update-accounts: update_accounts_topic
  delete-accounts: delete_accounts_topic
  new-following: new_following

server:
  port: 8090
  error:
    include-message: always